# =============================================================================
# pages/3_Barbers.py — Barbers / Team Page
# =============================================================================
# Displays a team grid of barber cards.
# Each card shows: avatar image, name, specialty badge, and bio.
# Cards are generated by looping over the BARBERS list in data.py.
#
# Key demo points for interviews:
#   - The same technique (loop over data → generate HTML) is used in real
#     frameworks like Django templates or React .map() calls
#   - Avatar images come from DiceBear (free, no API key needed) — the URL
#     takes a "seed" string and returns a consistent illustrated avatar SVG
#   - Layout uses st.columns() to create a responsive 2×2 grid
# =============================================================================

import streamlit as st
import os
import sys

# Add project root to Python's module search path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from data import BARBERS   # list of barber dicts from data.py

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(page_title="Our Team | The Sharp Edge", page_icon="👥", layout="wide")

# ── CSS injection ─────────────────────────────────────────────────────────────
def load_css():
    """Loads the global CSS stylesheet into the page."""
    css_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "style.css")
    if os.path.exists(css_path):
        with open(css_path, "r", encoding="utf-8") as f:
            st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

load_css()


# ===========================================================================
# PAGE HEADER
# ===========================================================================

st.markdown("""
    <h1>👥 Meet Our Team</h1>
    <p style='color:#9a9a9a; font-size:1.05rem; margin-bottom:2rem;'>
        Every barber at The Sharp Edge brings passion, precision, and personality.
        Find your perfect match and book with them directly.
    </p>
    <hr class="gold-divider">
""", unsafe_allow_html=True)


# ===========================================================================
# BARBER CARDS GRID
# ===========================================================================
# We render cards in a 2-column grid. To do that with a dynamic list, we
# use a technique called "chunking": split the list into pairs and put each
# pair in a row of two columns.
#
# Example with 4 barbers:
#   Row 1 → col1: BARBERS[0]   col2: BARBERS[1]
#   Row 2 → col1: BARBERS[2]   col2: BARBERS[3]
# ===========================================================================

# Determine how many columns per row (2 here; easy to change to 3 or 4)
COLS_PER_ROW = 2

# Loop through the BARBERS list, stepping by COLS_PER_ROW each iteration
# range(0, 4, 2) → [0, 2]  → generates starting indexes for each row
for row_start in range(0, len(BARBERS), COLS_PER_ROW):

    # Slice the list to get just the barbers for this row
    # e.g. BARBERS[0:2] → first two, BARBERS[2:4] → next two
    row_barbers = BARBERS[row_start : row_start + COLS_PER_ROW]

    # Create one column per barber in this row
    cols = st.columns(COLS_PER_ROW)

    # Loop through the barbers for this row and fill each column
    for col, barber in zip(cols, row_barbers):
        with col:
            # Build the barber card HTML using the barber dict values
            card_html = (
                '<div class="barber-card">'
                '<div class="barber-avatar">'
                f'<img src="{barber["image_url"]}" alt="Photo of {barber["name"]}" loading="lazy">'
                '</div>'
                f'<div class="barber-name">{barber["name"]}</div>'
                f'<div class="specialty-badge">{barber["specialty"]}</div>'
                f'<p class="barber-bio">{barber["bio"]}</p>'
                '</div>'
            )
            st.markdown(card_html, unsafe_allow_html=True)

            # Native Streamlit button below each card
            # Button label includes the barber's first name for personalization
            first_name = barber['name'].split()[0]   # split "Marcus Reeves" → take "Marcus"
            if st.button(f"Book with {first_name}", key=f"book_{barber['name']}",
                         use_container_width=True):
                # Navigate to the booking page; the user can then pick this barber from the dropdown
                st.switch_page("pages/4_Book_Appointment.py")

        # Add vertical spacing between rows
        st.markdown("<div style='height:1rem;'></div>", unsafe_allow_html=True)


# ===========================================================================
# TEAM STATS SECTION
# ===========================================================================
# Fun metrics calculated from the BARBERS list — shows dynamic rendering.
# ===========================================================================

st.markdown('<hr class="gold-divider">', unsafe_allow_html=True)

st.markdown("<h2 style='text-align:center;'>The Team at a Glance</h2>",
            unsafe_allow_html=True)

# Calculate stats
total_barbers = len(BARBERS)                         # total number of barbers
specialties   = [b["specialty"] for b in BARBERS]   # list of all specialty strings

# Three metric columns
s1, s2, s3 = st.columns(3)

with s1:
    # Total barbers on the team
    st.metric("Team Members", total_barbers, help="Full-time barbers on staff")

with s2:
    # Combined years of experience — static number for demo purposes
    # In a real app this would come from the DB
    st.metric("Combined Years Exp.", "35+", help="Total years of professional barbering experience")

with s3:
    # How many distinct specialties the team covers
    st.metric("Specialties Covered", len(set(specialties)),
              help="Unique areas of expertise across the team")


# ===========================================================================
# "JOIN THE TEAM" FOOTER SECTION
# ===========================================================================

st.markdown('<hr class="gold-divider">', unsafe_allow_html=True)

st.markdown("""
    <div class="info-card" style="text-align:center;">
        <div style="font-size:2rem; margin-bottom:0.8rem;">🤝</div>
        <div class="info-card-title">Interested in Joining Our Team?</div>
        <p style="color:#9a9a9a; font-size:0.95rem; max-width:500px; margin:0 auto;">
            We're always looking for passionate, skilled barbers to grow with us.
            Reach out via our Contact page and let's talk.
        </p>
    </div>
""", unsafe_allow_html=True)

# Link to contact page
if st.button("✉️ Get in Touch", use_container_width=False):
    st.switch_page("pages/6_Contact.py")
